baseURL = "https://dekim.github.io/tgbot_practic/"
locale = "ru"
title = "Проектная практика 2026"
theme = "clarity"
publishDir = "../docs"

[[menu.main]]
  name = "О проекте"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Проектная практика"
  url = "/participants/"
  weight = 2

[params]
  numberOfRecentPosts = 0
  mainSections = [ ]
  customCSS = ["css/custom.css"]
  [params.author]
    name = "Автор"
    email = "str7503@mail.ru"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


